name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - working-directory: ./streamlit_supabase_auth/frontend
        run: npm install
      - working-directory: ./streamlit_supabase_auth/frontend
        run: npm run test
